[package]
name = "howl"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
itertools = "0.4.16"
rand = "0.3.14"
num = "0.1.32"
rustty = { git = "https://github.com/stevebob/rustty.git" }

[features]
hash_map_table = []
