imports = [
    "game::components::DoorState",
    "game::components::AxisVelocity",
    "geometry::Vector2",
]

[component.position]
    type = "Vector2<isize>"

[component.axis_velocity]
    type = "AxisVelocity"

[component.solid]

[component.collider]

[component.opacity]
    type = "f64"

[component.door]
    type = "DoorState"

[query.movement]
    prefix = "Movement"
    components = ["position", "solid", "axis_velocity"]

[action_property.name]
    type = "&'static str"

[action_property.turn_time]
    type = "u64"

[action_property.action_time]
    type = "u64"

[action_property.axis_velocity_movement]
