ecs_core_namespace = "ecs_core"
ecs_content_namespace = "ecs_content"

position = 'position'

fields = [
    { name = 'opacity', aggregate = 'sum_f64' },
    { name = 'solid', aggregate = 'any' },
    { name = 'enemy', aggregate = 'any' },
    { name = 'pc', aggregate = 'count_bool' },
    { name = 'level_switch', aggregate = 'any' },
    { name = 'floor', aggregate = 'any' },
    { name = 'tile', aggregate = 'void' },
]
