imports = [
    "ecs_core::*",
    "math::*",
    "engine_defs::*",
    "message::*",
    "content_types::*",
    "tile::TileType",
    "util::ScheduleTicket",
]

flags = [
    { name = 'solid' },
    { name = 'pc' },
    { name = 'floor' },
    { name = 'enemy' },
    { name = 'health_bar' },
    { name = 'should_render' },
]

data = [
    { name = 'tile', type = 'TileType', copy = true },
    { name = 'position', type = 'Coord', copy = true },
    { name = 'opacity', type = 'f64', copy = true },
    { name = 'vision_distance', type = 'usize', copy = true },
    { name = 'tile_depth', type = 'isize', copy = true },
    { name = 'behaviour_type', type = 'BehaviourType', copy = true },
    { name = 'turn_offset', type = 'u64', copy = true },
    { name = 'turn_time', type = 'u64', copy = true },
    { name = 'shadow_entity', type = 'EntityId', copy = true },
    { name = 'schedule_ticket', type = 'ScheduleTicket', copy = true },
    { name = 'level_switch', type = 'LevelSwitch', copy = true },
    { name = 'level_switch_group', type = 'usize', copy = true },
    { name = 'probabilistic_animation', type = 'FirstWeightedProbabilisticChoice<TileType>' },
    { name = 'behaviour_state', type = 'BehaviourState' },
    { name = 'path_traverse', type = 'PathTraverse' },
    { name = 'name', type = 'NameMessageType', copy = true },
    { name = 'description', type = 'DescriptionMessageType', copy = true },
    { name = 'hit_points', type = 'HitPoints', copy = true },
]

cells = [
    { name = 'message_log', type = 'MessageLog' },
    { name = 'drawable_knowledge', type = 'DrawableKnowledge' },
    { name = 'simple_npc_knowledge', type = 'SimpleNpcKnowledge' },
]

action_flags = [
    { name = 'no_commit' },
    { name = 'player_died' },
    { name = 'physics' },
    { name = 'realtime_delay' },
    { name = 'start_realtime_move' },
]

action_data = [
    { name = 'then', type = "Reaction", copy = true },
    { name = 'alternative_turn_time', type = "u64", copy = true },
    { name = 'action_time_ms', type = "u64", copy = true },
    { name = 'level_switch_action', type = "LevelSwitchAction", copy = true },
    { name = 'try_level_switch', type = "EntityId", copy = true },
    { name = 'projectile_collision', type = "ProjectileCollision", copy = true },
    { name = 'schedule_invalidate', type = "ScheduleTicket", copy = true },
    { name = 'action_description', type = 'ActionDescription' },
]
